import "./assets/main.scss";

import { createApp } from "vue";
import App from "./App.vue";

import router from "./router";
import { createPinia } from "pinia";
import { createI18n } from "vue-i18n";

import "./assets/tailwind.css";
const pinia = createPinia();

const messages = {
  kor: {
    // header
    hire: "고용하기",
    info: "이용안내",
    price: "요금안내",
    reserve: "예약하기",
    review: "고객후기",
    cs: "고객센터",
    login: "로그인",
    logout: "로그아웃",
    mypage: "마이페이지",
    mainBanner: [
      {
        title1: "무거운 짐",
        title2: "짐꾼이 옮겨드립니다!",
        title3: "짐꾼은 무거운 여행짐을",
        title3Span: "집에서 숙소",
        title3After: "까지",
        title4Span: "",
        title4: "대신 들어드리는 여행 도우미 입니다.",
        image: "/images/hong/slideImg1.png",
        imageWidth: "400px",
      },
      {
        title1: "간단한 예약",
        title2: "짐꾼은 많이 묻지 않습니다!",
        title3: "짐꾼의 몇 번의 클릭으로",
        title3Span: "빠르고 편리하게",
        title3After: "",
        title4Span: "",
        title4: "예약할 수 있습니다.",
        image: "/images/hong/slideImg2.png",
        imageWidth: "400px",
      },
      {
        title1: "직접 찾아갑니다",
        title2: "간단하고 편리한 서비스!",
        title3: "짐꾼은 고객님이 앞에 두신 짐을",
        title3Span: "",
        title3After: "",
        title4Span: "직접 찾아가서",
        title4: "수거해갑니다.",
        image: "/images/hong/slideImg3.png",
        imageWidth: "350px",
      },
      {
        title1: "여행은 가볍게",
        title2: "짐꾼이 짐을 맡아드립니다!",
        title3: "짐꾼은 고객님의 소중한 짐을",
        title3Span: "",
        title3After: "",
        title4Span: "안전하게 보관",
        title4: "해드립니다.",
        image: "/images/hong/slideImg4.png",
        image1: "/images/hong/slideImg4-1.png",
        imageWidth: "280px",
      },
    ],
// A1_home
    pickup: "출발지",
    athome: "짚 앞",
    scheduled: "짐 맡길 일정",
    destination: "도착지",
    station: "서울역",
    pickuptime: "짐 찾을 일정",
    reservation: "바로예약",
    benefits: "짐꾼 혜택",
    checkbenefits1: "지금 받을 수 있는",
    checkbenefits2: "혜택을 확인해보세요.",
    allBenefits: "짐꾼 혜택 몰아보기",
    appDownload: "앱 다운로드 고객 한정 할인 중",
    thoroughCare: "꼼꼼하게 지키는 짐꾼 케어",
    options: "다양하게 보장되는 보험들을 체크해보세요.",
    guide: "외국인 이용 가이드",
    business: "해외출장",
    travelFree: "여행가방 걱정 끝",
    travelFree1: "짐꾼은 집 앞에서 역·공항으로, 역·공항에서 숙소로",
    travelFree2: "여행 짐을 안전하게 옮겨주는 캐리어 운반 서비스입니다.",
    businessTrip: "출장 갈 때,",
    businessTripSpan: " 더 편하게 짐꾼!",
    TravelLight1: "미팅 끝나고 가는 출장까지,",
    TravelLight2: "짐은 짐꾼에 맡기고 두 손 가볍게",
    TravelLight3: "이동하세요!",
    week: "주말여행",
    weektrip1: "주말여행,",
    weektrip2: "더 빠르게 짐꾼! ",
    weektriptext1: "짧은 주말을 이용해 떠나는 여행!",
    weektriptext2: "회사에 들고가자니 눈치보이는",
    weektriptext3: "캐리어 짐꾼이 먼저 옮겨드릴게요!",
    golf:"골프투어",
    golf1:"골프투어도,",
    golf2:"더 즐겁게 짐꾼!",
    golfText1:"골프, 스쿠버다이빙, 서핑, 스키!",
    golfText2:"즐거운만큼 무거운 취미 용품들",
    golfText3:"짐꾼이 안전하게 배송해드릴게요!",
    Evening: "퇴근여행",
    Evening1: "퇴근 후에도,",
    Evening2: "더 가볍게 짐꾼!",
    Eveningtext1: "사람 많고, 정신없는 출근시간",
    Eveningtext2: "지옥철에 크고 무거운 캐리어와",
    Eveningtext3: "함께 타는 건 이제 그만!",
    jimggun:"짐꾼",
    download:"앱 다운받기",
    journeywithoutluggage:"여행가방 없이 떠나는 새로운 여행",
    experienceitwithMovers:"짐꾼에서 경험하세요!",
    Android: "안드로이드",
    coupon: "짐꾼이 처음인 당신을 위한 쿠폰 혜택!",
    coupontext1: "신규 회원에게 즉시 사용 가능한 쿠폰을 드립니다.",
    coupontext2: "할인 혜택으로 여행을 가볍게 시작하세요.",
    // footer
    boss:"대표자 : 1조",
    address:"주소 : 대구 중앙대로 394 제일빌딩 5F",
    businessNumber:"사업자등록번호 : 123-45-67890",
    privacyOfficer: "개인정보보호책임자 : 1조",
    email:"이메일",
    operating:"오전 9시 ~ 오후 6시",
    holiday:"(토요일, 공휴일 휴무)",
    partnership:"제휴문의",
    cs:"고객센터",
    termsService: "서비스 이용약관",
    privacyPolicy: "개인정보처리방침",
  },
  eng: {
    // header
    hire: "Hire now",
    info: "Information",
    price: "Pricing",
    reserve: "Reservation",
    review: "Reviews",
    cs: "Support",
    login: "Login",
    logout: "Logout",
    mypage: "My Page",
    // A1_home
    mainBanner: [
      {
        title1: "Heavy luggage",
        title2: "Jimggun carries it for you!",
        title3: "Jimggun carries your heavy luggage",
        title3Span: "from home to hotel",
        title3After: "",
        title4Span: "",
        title4: "Your travel helper that carries it for you.",
        image: "/images/hong/slideImg1.png",
        imageWidth: "400px",
      },
      {
        title1: "Simple Reservation",
        title2: "Jimggun won't ask much!",
        title3: "With just a few clicks,",
        title3Span: "fast and easy",
        title3After: "",
        title4Span: "",
        title4: "you can make a reservation.",
        image: "/images/hong/slideImg2.png",
        imageWidth: "400px",
      },
      {
        title1: "Direct Pickup",
        title2: "Simple and convenient service!",
        title3: "Jimggun will pick up your luggage",
        title3Span: "directly from your location",
        title3After: "",
        title4Span: "",
        title4: "and deliver it safely.",
        image: "/images/hong/slideImg3.png",
        imageWidth: "350px",
      },
      {
        title1: "Travel Light",
        title2: "Let Jimggun handle your luggage!",
        title3: "Jimggun will safely store",
        title3Span: "your valuable belongings",
        title3After: "",
        title4Span: "",
        title4: "while you travel worry-free.",
        image: "/images/hong/slideImg4.png",
        image1: "/images/hong/slideImg4-1.png",
        imageWidth: "280px",
      },
    ],
    pickup: "Pickup Location",
    athome: "At home",
    scheduled: "Scheduled Pickup Time",
    destination: "Drop-off Location",
    station: "seoul station",
    pickuptime: "Pickup Date",
    reservation: "Book Now",
    benefits: "Jimggun's Benefits",
    checkbenefits1: "Check out the benefits",
    checkbenefits2: "you can get now.",
    allBenefits: "See All Benefits",
    appDownload: "App-Only Discount",
    thoroughCare: "Meticulous Care",
    options: "Explore our insurance options.",
    guide: "Foreign User Guide",
    travelFree: "TRAVEL LIGHT, WORRY-FREE",
    travelFree1: "Jimggun safely delivers your luggage",
    travelFree2: "from your home to the station or airport, and then to your accommodation.",
    business: "Business",
    businessTrip: "Business Trip?",
    businessTripSpan: "Go Light with Jimggun!",
    TravelLight1: "Meetings or business trips,",
    TravelLight2: "Leave your luggage to us,",
    TravelLight3: "Travel hands-free!",
    week:"Weekend",
    weektrip1: "Weekend trip?",
    weektrip2: "Jimggun, fast and ready!",
    weektriptext1: "Short weekend getaway!",
    weektriptext2: "Suitcase feels awkward at work.",
    weektriptext3: "We’ll move it for you!",
    golf:"Golf",
    golf1:"Golf tour?",
    golf2:"Jimggun make it fun!",
    golfText1:"Golf, scuba diving, surfing, skiing!",
    golfText2:"Heavy gear for your fun hobbies",
    golfText3:"We deliver them safely for you!",
    Evening: "After-work",
    Evening1: "After-work trips,",
    Evening2: "travel light with Jimggun!",
    Eveningtext1: "Rush hour crowds.",
    Eveningtext2: "No more heavy suitcases.",
    Eveningtext3: "Travel stress-free!",
    jimggun:"JIMGGUN",
    download:"Download",
    journeywithoutluggage:"A new journey without luggage.",
    experienceitwithMovers:"Experience it with Jimggun!",
    Android: "Android",
    coupon: "Welcome coupon for newbies!",
    coupontext1: "New members get an instant-use coupon upon sign-up!",
    coupontext2: "Start your trip lighter with a discount!",
    // footer
    boss:"Team Leader: Team 1",
    address:"Address: 5th Floor, Jeil Building, 394 Jungang-daero, Daegu",
    businessNumber:"Business Registration Number: 123-45-67890",
    privacyOfficer: "Privacy Officer: Team 1",
    email:"E-mail",
    operating:"9:00 AM – 6:00 PM",
    holiday:"(Closed on Saturdays and public holidays)",
    partnership:"Partnership",
     support:"Customer Support",
    termsService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
  },
};

const i18n = createI18n({
  legacy: false, // ✅ Composition API 모드로 설정
  locale: "kor",
  fallbackLocale: "eng",
  messages,
});

const app = createApp(App);
app.use(pinia);
app.use(i18n);
app.use(router);
app.mount("#app");
